version: '3.8'

services:
  # Nodo Caracas
  postgres-caracas:
    image: postgres:15-alpine
    container_name: bd-caracas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/caracas/init.sql:/docker-entrypoint-initdb.d/init.sql
      - caracas-data:/var/lib/postgresql/data
    networks:
      bd-network:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Nodo Valencia
  postgres-valencia:
    image: postgres:15-alpine
    container_name: bd-valencia
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/valencia/init-distribuido.sql:/docker-entrypoint-initdb.d/init.sql
      - valencia-data:/var/lib/postgresql/data
    networks:
      bd-network:
        ipv4_address: 172.20.0.11
    depends_on:
      postgres-caracas:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bd-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - bd-network
    depends_on:
      - postgres-caracas
      - postgres-valencia

networks:
  bd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  caracas-data:
  valencia-data:
  pgadmin-data: 